### ISSUE TITLE
Why resume()?

### ISSUE THREAD

**Issue by gvilarino** [elad/node-cluster-socket.io#11]
I've been trying [`sticky-session`](https://github.com/indutny/sticky-session) with a 4-process cluster and it seems to be working.

However, on your example you mention explicitly the need to call `resume()` for a slave to take over incoming socket data. The thing is, [`sticky-session` doesn't use `resume()`](https://github.com/indutny/sticky-session/blob/master/lib/sticky/api.js#L22-L28) and it seems to be working nonetheless.

¿Could you please shed some light? I'm really new to this.

**Comment by elad** [comment]
From the documentation:

> If pauseOnConnect is true, then the socket associated with each incoming connection will be paused, and no data will be read from its handle. This allows connections to be passed between processes without any data being read by the original process. To begin reading data from a paused socket, call resume().

**Comment by gvilarino** [comment]
so `sticky-session`'s author [just clarified](https://github.com/indutny/sticky-session/issues/31#issuecomment-138690512) that workers automatically resume sockets when receiving them. Closing this.
