### ISSUE TITLE
Correct Approach?

### ISSUE THREAD

**Issue by manast** [elad/node-cluster-socket.io#25]
Seems to me that the approach proposed in this repo is not the correct one, and I am almost inclined to define it as an anti-pattern. 
My reasoning is that socket.io should be cluster and loadbalancer compatible from the group up. It is much easier to make socket.io work well with multiple servers than trying to solve this issue on top of it. For socket-io is just a matter of using a persistent, distributed store such as redis (or any database for that matter), to store the connection/session data, so that the communication can be established even if the client hits several servers during the lifetime of a socket.io session. 
All these other solutions trying to bend the natural behaviours of the cluster module and loadbalancers are just going to bring pain and despair to people...

**Comment by elad** [comment]
I believe you're looking for [socketio/socket.io](https://github.com/socketio/socket.io/)

**Comment by manast** [comment]
I was not. The problem is that this repo may give the impression that this is a good solution as if it was something intrinsic with socket.io that made it impossible to work with loadbalancers out of the box...when it is just a shortcoming with not a so difficult solution. I can put a similar issue in socket.io and link them together though.

**Comment by lxcid** [comment]
@manast I agree with you and socket.io already have a Redis backed database for broadcasting.

But it seems that the handshaking info are stored in memory, rather than in a database. Not sure where we can extend that. This behaviour is in [engine.io](https://github.com/socketio/engine.io). Do you have a solution to this?

Rather than relying on sticky session?

**Comment by manast** [comment]
My solution has been to use websockets directly... it is supported everywhere nowadays so no much use for engine.io.

**Comment by lxcid** [comment]
I see, thanks! 👍
