### ISSUE TITLE
How to resolve mutiple message coming when client send a mesage?

### ISSUE THREAD

**Issue by chunhui2001** [elad/node-cluster-socket.io#26]
I put some code to your example as below bold font marked: 
.................
process.on('message', function(message, connection) {
    if (message !== 'sticky-session:connection') {
        return;
    }
    **io.sockets.on('connection', function(socket) {
        socket.on('set username ' + socketId, function(data, callback) {
    	     console.log('set', 1);			
        });
   });**
    server.emit('connection', connection);
    connection.resume();
});
...............
But console.log('set', 1); print mutiple times every message coming, How to avoid this problem?

**Comment by elad** [comment]
Sorry, this is unrelated.
