### ISSUE TITLE
connection.remoteAddress is undefined

### ISSUE THREAD

**Issue by DefrenneD** [elad/node-cluster-socket.io#7]
Hi everybody,

I'm using nginx as a reverse-proxy and connection.remoteAddress is undefined.

    var server = net.createServer(function(connection) {
    ...
    connection.remoteAddress //undefined
    ...
    }).listen('/tmp/node.sock');

Do you have any ideas how I could get the IP ?

When i'm testing without nginx everything is fine.

**Comment by elad** [comment]
Closing for the same reason as #15.

**Comment by davidolen** [comment]
@barisusakli 

Just interested, when you were "dropping node cluster and spawning workers on different ports", did you start each worker process using a separate command "node app.js"? Or did you use another module to create and manage the worker processes? Also, what is the performance (and reliability)? 

Thanks!
