### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by theoneapc** [elad/node-cluster-socket.io#8]
This works great.
Could you please suggest if (and how) this can work for HTTPS server?

Thank you.

**Comment by elad** [comment]
In my setup everything is running behind an https-only nginx, so this absolutely works for https. However, using https directly in the node.js app is beyond the scope of this project.

**Comment by afrantz** [comment]
This works great too for me.
But i tried to modify my nginx confiuguration to enable only HTTPS and i get this error in my console on Chrome :
net::ERR_INSECURE_RESPONSE

This is my nginx configuration :
server {
    listen 443 ssl;
    server_name mydomain;

    location / {
        proxy_pass https://localhost:8030;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

Can you share your nginx configuration ?

Thank you.

**Comment by elad** [comment]
By proxying to https://localhost you force the listening program (node.js) to support SSL itself. I believe that's not proper layering and that SSL should only happen between the outside world and your server. Communication from localhost to localhost should not require SSL. In other words, proxy to http://localhost, not https. :)

**Comment by afrantz** [comment]
Indeed, this works with htpps now, thanks you ;)

**Comment by MickL** [comment]
Is Nginx/Apache really required? For example in Express.js i can activate SSL by giving it a certificate:

```
const app = express();
const privateKey  = fs.readFileSync(config.sslPrivateKey, 'utf8');
const certificate = fs.readFileSync(config.sslCert, 'utf8');
const credentials = {key: privateKey, cert: certificate};
const httpsServer = https.createServer(credentials, app);
httpsServer.listen(3000);
```
